;;; name: vim-keybindings
;;; version: 0.1.0
;;; description: Vim-style modal keybindings

;; Create normal-mode keymap with hjkl navigation and editing commands
(make-keymap "normal-mode")
(define-key "normal-mode" "Char:h" "cursor-left")
(define-key "normal-mode" "Char:j" "cursor-down")
(define-key "normal-mode" "Char:k" "cursor-up")
(define-key "normal-mode" "Char:l" "cursor-right")
(define-key "normal-mode" "Char:i" "enter-insert-mode")
(define-key "normal-mode" "Char:I" "insert-at-line-start")
(define-key "normal-mode" "Char:a" "insert-after-cursor")
(define-key "normal-mode" "Char:A" "insert-at-line-end")
(define-key "normal-mode" "Char:o" "open-line-below")
(define-key "normal-mode" "Char:O" "open-line-above")
(define-key "normal-mode" "Char:x" "delete-char-at-cursor")
(define-key "normal-mode" "Char:d" "delete-line")
(define-key "normal-mode" "Char:0" "cursor-line-start")
(define-key "normal-mode" "Char:$" "cursor-line-end")
(define-key "normal-mode" "Char:^" "cursor-first-non-blank")
(define-key "normal-mode" "Char:g" "cursor-document-start")
(define-key "normal-mode" "Char:G" "cursor-document-end")
(define-key "normal-mode" "Char:w" "cursor-word-forward")
(define-key "normal-mode" "Char:b" "cursor-word-backward")
(define-key "normal-mode" "Char:e" "cursor-word-end")
(define-key "normal-mode" "Char:J" "join-lines")
(define-key "normal-mode" "Char:y" "yank-line")
(define-key "normal-mode" "Char:p" "paste-below")
(define-key "normal-mode" "Char:c" "change-line")
(define-key "normal-mode" "Char:C" "change-to-end")
(define-key "normal-mode" "Char:u" "undo")
(define-key "normal-mode" "Ctrl:r" "redo")
(define-key "normal-mode" "Char:H" "cursor-screen-top")
(define-key "normal-mode" "Char:M" "cursor-screen-middle")
(define-key "normal-mode" "Char:L" "cursor-screen-bottom")
(define-key "normal-mode" "Ctrl:d" "scroll-half-page-down")
(define-key "normal-mode" "Ctrl:u" "scroll-half-page-up")
(define-key "normal-mode" "Char:f" "enter-char-find-forward")
(define-key "normal-mode" "Char:F" "enter-char-find-backward")
(define-key "normal-mode" "Char:t" "enter-char-til-forward")
(define-key "normal-mode" "Char:T" "enter-char-til-backward")
(define-key "normal-mode" "Char:;" "repeat-char-find")
(define-key "normal-mode" "Char:," "reverse-char-find")
(define-key "normal-mode" "Char::" "enter-command-mode")
(define-key "normal-mode" "Char:/" "enter-search-mode")
(define-key "normal-mode" "Char:n" "search-next")
(define-key "normal-mode" "Char:N" "search-prev")
(define-key "normal-mode" "Char:." "repeat-last-change")
(define-key "normal-mode" "Char:%" "match-bracket")
(define-key "normal-mode" "Char:>" "indent-line")
(define-key "normal-mode" "Char:<" "unindent-line")
(define-key "normal-mode" "Up" "cursor-up")
(define-key "normal-mode" "Down" "cursor-down")
(define-key "normal-mode" "Left" "cursor-left")
(define-key "normal-mode" "Right" "cursor-right")

;; Create insert-mode keymap with Escape, Backspace, and arrow keys
(make-keymap "insert-mode")
(define-key "insert-mode" "Escape" "enter-normal-mode")
(define-key "insert-mode" "Backspace" "delete-backward")
(define-key "insert-mode" "Up" "cursor-up")
(define-key "insert-mode" "Down" "cursor-down")
(define-key "insert-mode" "Left" "cursor-left")
(define-key "insert-mode" "Right" "cursor-right")

;; Define mode-switching commands
(define-command "enter-insert-mode" (lambda () (set-mode "insert")))
(define-command "enter-normal-mode" (lambda () (set-mode "normal")))

;; Set mode-aware cursor shapes
(set-cursor-shape "normal" "block")
(set-cursor-shape "insert" "bar")

;; Start in normal mode
(set-active-keymap "normal-mode")
(set-mode "normal")
